Exception has occurred: ConnectionError
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

  File "<string>", line 3, in raise_from

During handling of the above exception, another exception occurred:

  File "<string>", line 3, in raise_from

During handling of the above exception, another exception occurred:

  File "C:\Users\MEDIUM\Code\crypto\arbi1\exchange\bn.py", line 73, in bn_spot_1st_ask
    depth = client.get_order_book(symbol=pair)
  File "C:\Users\MEDIUM\Code\crypto\arbi1\arbi\arbi.py", line 33, in wait_kimp_inTh
    bn_p_usd, _  = bn_spot_1st_ask(binance, bn_pair) #market

->  언제든지 커넥션 에러 나올 수 있음.
-->try catch로 잡아서...?
-->withdraw에선 그냥 죽어도됨
-->trade중에만 복구코드... 어렵.. ㅜㅜ
-->일단 집적트레이드해야.. kimp alert -> program manual execution?
-->날아간것만 다시 트레이드 하는 코드 넣기.


#시간이 너무 오래 걸려서 async로 변환 필요. 
(0)ub_wait_deposit: state=ACCEPTED
[arbi_in_ubSpotSell_bnFutBuy] bn_fut_1st_ask(94ms), ub_spot_1st_bid(37ms)
[wait_kimp_inTh](0) kimp(2.01) > inTh(0.0) ?
[bn_fut_BUY]EOSUSDT 4.0q @ 4.877$, TEST=False
[ub_spot_sell]KRW-EOS 4.0q @ 5950.0W(4.9749$), TEST=False
[arbi_in_ubSpotSell_bnFutBuy] bn_fut_trade(54ms), ub_spot_trade(111ms)

1014
-withdraw fee db
-threading -> async

1015.
short 가능한 여러 코인 중 가장 min_out으로 나갔다가, 
최소 gain을 기준으로 다시 들어오기

김프의 큰 방향성의 가정은 있어야 함. 오를지 내릴지. 
 - 오를 것 같으면 달러로 
 - 내릴 것 같으면 원화로 마무리
-> 미래는 알 수 없다.
-> 그저 박스권 가정에 따라 기계적으로 움직이는 수준.
-> 리스크를 테이킹하고 시간과 인내를 할 수 밖에 없음.
-> 일단 지금 할 수 있는 건 aync통해 정교하게 하기. 한번에 다움직일 수 있게 하기. 호가별로 걸어두기.
-> flow처럼 다른 거래소에 기회 있는지 보기 (dex는 왜 안되지 흠 무조건 마이너스가 되는 방향으로 나오네) <- 성호형
-> 무지성으로 0.5%? 1%윈도우 잡고 사고 파는것도 방법이 될수 있을까. 벡테스팅.mrf 업데이트.*
-> async, 나갈때 싼 코인. 들어올땐 eos. 전략 테스팅 정도가 답일듯.. 박스권 말도 움직일때도 대응 가능한 전략 짜서 꾸준히 벌어볼 수 있는 방법 찾기.


-> in/out batch? process 분리? 

10.25
Exception has occurred: ReadTimeout       (note: full exception trace is shown but execution is paused at: <module>)
HTTPSConnectionPool(host='fapi.binance.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

  File "<string>", line 3, in raise_from

During handling of the above exception, another exception occurred:

24480sec kimp in wait_kimp_inTh
ex.binance.futures_order_book(symbol)

모든 error에 대해 depence 필요. 
